#️⃣주요 기능 개선 사항 (Optional)
DEU-CS-24-02/TextBasedRPGFramework pull request #19
Opened 2024-12-02 14:11 UTC by 20212936

REMOVE ME
"아이템 쿨타임, 강화 기능 구현"

🗒️ 커밋 정보 (Required)
REMOVE ME

"아이템 쿨타임 기능 추가
 - 일정 턴 지나지 않았을 경우 아이템이 사용할 수 없도록 하는 메서드 구현 아이템 강화 기능 추가
 - 강화 성공 확률을 랜덤으로 하고 강화 성공시 스탯 증가 구현"

❓ 리뷰시 참고 / 피드백 요청 사항 (Optional)
REMOVE ME

PR을 리뷰할 때 리뷰어가 참고, 또는 리뷰어에게 질문할 점을 적어주세요.

ItemComponents에도 새로 추가했는데 다른 부분은 건드리지 말고 ItemStack에만 메서드를 추가하도록 하나요? 아니면 필요에 따라 ItemComponents에도 추가하나요?

## #️⃣주요 기능 개선 사항 (Optional)

> REMOVE ME <br>
> 만약 특정 버그(이슈)를 수정했을 경우 해당 이슈를 링크해주세요. <br>
> 없을 경우 비워주시면 됩니다.

## 🗒️ 커밋 정보 (Required)
> REMOVE ME <br>
> 전반적인 PR에 대한 내용을 적어주세요. <br>
> 어떤 커밋을 했나요? 어떤 기능을 추가했나요? 어떤 문제를 해결했나요? <br>

## ❓ 리뷰시 참고 / 피드백 요청 사항 (Optional)

> REMOVE ME <br>
> PR을 리뷰할 때 리뷰어가 참고, 또는 리뷰어에게 질문할 점을 적어주세요. <br>
> Ex) ComponentMap 클래스 내에 getAvailableComponents 명명이 적합한가요? or 로직좀 봐주세요. 등등

2024-12-04 12:00 UTC, biryeongtrain requested changes
고생하셨습니다! 리뷰 확인하시고 해당부분 보완해주세요!

2024-12-04 12:00 UTC, biryeongtrain commented on src/main/java/net/biryeongtrain/text_emulator/item/ItemStack.java
> +        this.set(ItemComponents.ARMOR, 5.0f); // 기본 방어력
```suggestion
```

해당 부분은 ItemComponents 부분에 Default 에 존재해야겠죠?
추가로 ItemStack은 무기만을 이야기하는 것이 아니기 때문에 이렇게 ItemStack에 기본값으로 공격력이나 방어력이 존재하면 안됩니다.

2024-12-04 12:00 UTC, biryeongtrain commented on src/main/java/net/biryeongtrain/text_emulator/item/ItemStack.java
> +    }
전반적으로 작성 잘해주셨습니다. 다만, 이렇게 추가적인 기능을 만드실 때는 어떤 기능을 추가했는지, 어떤 값을 추가했는지 작성하셔야 팀끼리 공유하기 편합니다.

2024-12-04 12:02 UTC, 20212936 commented on src/main/java/net/biryeongtrain/text_emulator/item/ItemStack.java
> +    }
넵 주의해서 올리겠습니다 감사합니다!

2024-12-05 18:09 UTC, biryeongtrain approved these changes
전반적으로 정말 잘 해주셨습니다! 특히 판매 부분이나 강화 부분에서도 고민하시고 추가하신게 느껴져서 더 좋았어요! 고생하셨습니다 :)

2024-12-05 18:10 UTC, merged