Add DESCRIPTION, DAMAGE, ARMOR, RARITY, DURABILITY
DEU-CS-24-02/TextBasedRPGFramework pull request #7
Opened 2024-10-18 11:54 UTC by 20212936

## #️⃣주요 기능 개선 사항 (Optional)

> REMOVE ME <br>
> 만약 특정 버그(이슈)를 수정했을 경우 해당 이슈를 링크해주세요. <br>
> 없을 경우 비워주시면 됩니다.

## 🗒️ 커밋 정보 (Required)
> REMOVE ME <br>
> 전반적인 PR에 대한 내용을 적어주세요. <br>
> 어떤 커밋을 했나요? 어떤 기능을 추가했나요? 어떤 문제를 해결했나요? <br>

## ❓ 리뷰시 참고 / 피드백 요청 사항 (Optional)

> REMOVE ME <br>
> PR을 리뷰할 때 리뷰어가 참고, 또는 리뷰어에게 질문할 점을 적어주세요. <br>
> Ex) ComponentMap 클래스 내에 getAvailableComponents 명명이 적합한가요? or 로직좀 봐주세요. 등등

2024-10-18 13:05 UTC, biryeongtrain commented
고생하셨습니다. 다음에는 PR 템플릿 채워서 올려주세요!
Suggestion 한 부분 수정하시면 됩니다.
https://nesoy.github.io/articles/2019-11/Github-suggestion
해당 글 읽고 커밋해주세요.

2024-10-18 13:19 UTC, biryeongtrain requested changes
고생하셨습니다. 다음에는 PR 템플릿 채워서 올려주세요!
Suggestion 한 부분 수정하시면 됩니다.
https://nesoy.github.io/articles/2019-11/Github-suggestion
해당 글 읽고 커밋해주세요.

2024-10-18 13:29 UTC, 20212936 reviewed
넵! 다음에는 보낼 때 PR탬플릿 채워서 보내겠습니다!

2024-10-19 15:14 UTC, biryeongtrain approved these changes
고생하셨습니다 :)

2024-10-19 15:14 UTC, merged